### PR TITLE
Update TokyoDrift

### PR DESCRIPTION
**Pull request by xesdoog**
- Add a few new features:
  - Nos now has screen effects (can be disabled)
  - Launch Control
  - Pops & Bangs (crackle tune)
  - Auto brake lights
  - Keep engine on (or hold F to turn off the engine)
  - Can't touch this! (prevent everyone from carjacking you)

### CODE REVIEW

**Comment by Deadlineem** [comment]
I only have one thing to have you add to this @xesdoog and thats to change the keybind for nos/speed boost as it messes with the drift mode, id like to be able to use them together.

**Comment by xesdoog** [comment]
> I only have one thing to have you add to this @xesdoog and thats to change the keybind for nos/speed boost as it messes with the drift mode, id like to be able to use them together.

Yeah I though of that yesterday actually when I was casually playing I wanted to hold bigger drift angles using NOS. I couldn't think of a convenient button that's comfortable for both keyboard and controller. Any suggestions?

**Comment by Deadlineem** [comment]
> > I only have one thing to have you add to this @xesdoog and thats to change the keybind for nos/speed boost as it messes with the drift mode, id like to be able to use them together.
> 
> Yeah I thought of that yesterday actually when I was casually playing I wanted to hold bigger drift angles using NOS. I couldn't think of a convenient button that's comfortable for both keyboard and controller. Any suggestions?

we ever figure this out?

**Comment by xesdoog** [comment]
> we ever figure this out?

No we haven't agreed on the buttons. I even forgot that this was open 😅
If you want to close it just change one of the buttons to 171 or something.

**Comment by Deadlineem** [comment]
> > we ever figure this out?
> 
> No we haven't agreed on the buttons. I even forgot that this was open 😅 If you want to close it just change one of the buttons to 171 or something.

Ill push this as is and take a look when i get home from work

**Comment by USBMenus** [comment]
you could check if theyre on keyboard and mouse with `PAD.IS_USING_KEYBOARD_AND_MOUSE(2)` and apply the keybinds as needed

**Comment by Deadlineem** [comment]
> you could check if theyre on keyboard and mouse with `PAD.IS_USING_KEYBOARD_AND_MOUSE(2)` and apply the keybinds as needed

I will check when i am home and see about this as well.

**Pull request merged**
