### PR TITLE
Custom set level, more teleports, small fixes and more.

### PR DESCRIPTION
**Pull request by juniorkrz**
- Added custom set level
- Added more teleports
- Keep the player in the vehicle when teleporting
- Deleting trailing spaces
- Small refactoring in CasinoPacino

### CODE REVIEW

**Review by Deadlineem — CHANGES_REQUESTED** [review]
"in the same row as "..casVal.." instead of '2 to 1'"

as of current its 

in the same row as the "..casVal.." number

**Comment by Deadlineem** [comment]
> * Added custom set level
> * Added more teleports
> * Keep the player in the vehicle when teleporting
> * Deleting trailing spaces
> * Small refactoring in CasinoPacino

For the RP level, does this actually convert the rp to level?  I see `rpLevel = ranks[chosenLevel]-- get rp level from ranks` but where is ranks defined?

Other than some grammatical issues for the casino revision, this looks good to me.

**Comment by juniorkrz** [comment]
> Other than some grammatical issues for the casino revision, this looks good to me. Nice job!

Only on line `3210` or on line `3195` as well?

**Comment by Deadlineem** [comment]
> > Other than some grammatical issues for the casino revision, this looks good to me. Nice job!
> 
> Only on line `3210` or on line `3195` as well?

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/00c6f25d0c4a8f13b990cda08225c10bc0b00361/Extras-Addon.lua#L3195

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/00c6f25d0c4a8f13b990cda08225c10bc0b00361/Extras-Addon.lua#L3210

Both of these.

**Comment by Deadlineem** [comment]
Im just gonna merge it and make the changes to the text areas then update it, everything else here is fine fr.

**Pull request merged**
